CREATE TABLE `df_site_application_registration` (
  `idx` int NOT NULL AUTO_INCREMENT,
  `wdate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_applicant_type` enum('P','O') NOT NULL COMMENT '접수유형 (P=개인, O=단체)',
  `f_item_idx` int NOT NULL COMMENT '자격종목',
  `f_category` enum('nail','hear','skin','half','foreign','teacher') NOT NULL COMMENT '자격분야',
  `f_schedule_idx` int NOT NULL COMMENT '시험일정 IDX (df_site_application.idx)',
  `f_user_name` varchar(100) NOT NULL COMMENT '이름 (단체인 경우 단체명)',
  `f_user_name_en` varchar(100) NOT NULL COMMENT '영문이름 (단체인 경우 담당자명)',
  `f_tel` varchar(20) DEFAULT NULL COMMENT '연락처',
  `f_birth_date` varchar(20) DEFAULT NULL COMMENT '생년월일',
  `f_contact_phone` varchar(20) DEFAULT NULL COMMENT '단체인 경우 담당자 연락처',
  `f_zip` varchar(10) DEFAULT NULL COMMENT '우편번호',
  `f_address1` varchar(255) DEFAULT NULL COMMENT '기본주소',
  `f_address2` varchar(255) DEFAULT NULL COMMENT '상세주소',
  `f_email` varchar(255) NOT NULL COMMENT '이메일',
  `f_application_type` enum('exam','certificate') NOT NULL COMMENT '신청구분 (exam=시험접수, certificate=자격증발급)',
  `f_issue_desire` tinyint(1) NOT NULL DEFAULT '0' COMMENT '자격증 발급희망 여부 (개인만)',
  `f_issue_file` varchar(255) DEFAULT NULL COMMENT '발급희망 시 파일 업로드',
  `f_payer_name` varchar(100) DEFAULT NULL COMMENT '입금자명',
  `f_payer_bank` varchar(100) DEFAULT NULL COMMENT '입금 은행',
  `f_payment_category` varchar(100) DEFAULT NULL COMMENT '입금구분 (중복가능: written=필기, practical=실기, issuance=발급비)',
  `f_user_idx` int DEFAULT NULL,
  `f_user_id` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='시험일정 접수 정보 테이블'