CREATE TABLE df_site_qualification (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    page_no TINYINT NOT NULL DEFAULT 1,
    f_name VARCHAR(255) NOT NULL,
    f_type VARCHAR(100) NOT NULL,
    f_reg_no VARCHAR(100) NOT NULL,
    f_manage_org VARCHAR(255) NOT NULL,
    f_ministry VARCHAR(255) NOT NULL,
    wdate DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;