CREATE TABLE `df_site_member` (
  `idx` int NOT NULL AUTO_INCREMENT,
  `wdate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_member_type` enum('P','O') NOT NULL COMMENT '회원 유형 (P=개인, O=단체)',
  `f_user_name` varchar(50) DEFAULT NULL COMMENT '이름',
  `f_birth_date` varchar(50) DEFAULT NULL COMMENT '생년월일',
  `f_gender` enum('M','F') DEFAULT NULL COMMENT '성별',
  `f_tel` varchar(15) DEFAULT NULL COMMENT '전화번호',
  `f_mobile` varchar(15) DEFAULT NULL COMMENT '휴대전화번호',
  `f_affiliation_flag` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '소속단체 여부 (N=없음, Y=있음)',
  `f_affiliation_name` varchar(255) DEFAULT NULL COMMENT '소속단체 이름',
  `f_org_name` varchar(255) DEFAULT NULL COMMENT '단체명',
  `f_org_phone` varchar(15) DEFAULT NULL COMMENT '단체 전화번호',
  `f_contact_name` varchar(50) DEFAULT NULL COMMENT '담당자명',
  `f_contact_phone` varchar(15) DEFAULT NULL COMMENT '담당자 연락처',
  `f_zip` varchar(10) DEFAULT NULL COMMENT '우편번호',
  `f_address1` varchar(255) DEFAULT NULL COMMENT '기본주소',
  `f_address2` varchar(255) DEFAULT NULL COMMENT '상세주소',
  `f_user_id` varchar(50) NOT NULL COMMENT '아이디(4~12자 영문/숫자)',
  `f_password` varchar(500) NOT NULL COMMENT '비밀번호(해시)',
  `f_email` varchar(255) NOT NULL COMMENT '이메일',
  `f_email_consent` enum('N','Y') NOT NULL DEFAULT 'Y' COMMENT '이메일 수신 동의',
  PRIMARY KEY (`idx`),
  UNIQUE KEY `f_user_id` (`f_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='개인/단체 회원 통합 테이블';